applicationName: CWDS CALS API
version: ${APP_VERSION:-local}

server:
  applicationConnectors:
  - type: http 
    port: 8080
  adminConnectors:
  - type: http
    port: 9081

shiro:
  iniConfigs: ["file:${SHIRO_CONFIG_PATH:-config/shiro.ini}"]

swagger:
  templateName: swagger.mustache
  assetsPath: /static
  resourcePackage: gov.ca.cwds.rest.resources
  title: CWDS API
  description: RESTful API definitions for the CWS New System.
  logo: images/CWDS-API-Logo-Horizontal.png
  loginUrl: ${LOGIN_URL:-http://localhost:8090/authn/login}
  showSwagger: ${SHOW_SWAGGER:-false}

nsDataSourceFactory:
  driverClass: org.postgresql.Driver
  user: ${DB_NS_USER:-postgres}
  password: ${DB_NS_PASSWORD:-postgres}
  url: ${DB_NS_JDBC_URL:-jdbc:postgresql://localhost:5432/postgres}
  validationQuery: "/* MyService Health Check */ SELECT 1"
  logValidationErrors: true
  initialSize: ${DB_NS_CP_INITIAL_SIZE:-2}
  minSize: ${DB_NS_CP_MIN_SIZE:-2}
  maxSize: ${DB_NS_CP_MAX_SIZE:-8}
  minIdleTime: 1 minute
  properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL82Dialect
      hibernate.id.new_generator_mappings: false
      hibernate.show_sql: true
